name : ci/cd pipeline

on : push main

jobs :
  build:
    runs-on: ubuntu-latest
    strategy :
      matrix: 
        go-version: '1.21.x'
    steps : 
      - uses: actions/checkou@v5
      - name: SETUP go ${{matrix.go-verion}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: Display go version
        run : go version
      - name: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
