name : ci/cd pipeline

on : 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs :
  build:
    runs-on: ubuntu-latest
   
    steps : 
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: SETUP go ${{matrix.go-verion}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - name: Display go version
        run : go version

      - name: Install dependencies 
        run : go mod download

      - name: run tests
        run: go test ./...

      - name: Build application 
        run : go build -v ./...

      - name: RUn LINTER
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...  
          
